# Generated by Django 4.1.2 on 2024-10-07 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_words_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
